#!/usr/bin/env python3
"""Generate Field / Type / Description reference pages for **external** schemas
that live in a sibling DEG repo, and embed them as GitBook/PDF pages in this repo.

Why this exists
---------------
The IES Accelerator book (GitBook + the `build_pdf.sh` PDF) is built entirely
from the Markdown files listed in ``SUMMARY.md``. To surface schemas that are
authored in another repository (the DEG monorepo: Energy Trading / P2P wave2 and
Demand Flexibility), we generate self-contained Markdown pages here from those
schemas' source and list them in ``SUMMARY.md``. GitBook renders them like any
other page; ``scripts/build_pdf.py`` concatenates them and even shrinks the
generated tables (it keys on the same ``<!-- FIELD-TABLE -->`` markers used by
``scripts/generate_field_tables.py``).

Difference from ``generate_field_tables.py``
--------------------------------------------
That sibling tool reads a *compiled* ``schema.json`` (a flat ``$defs`` map). The
DEG trading / demand-flex schemas have no ``schema.json`` — they are authored as
OpenAPI ``attributes.yaml`` (``components.schemas``) with ``allOf`` inheritance,
internal ``$defs``, ``schema.beckn.io`` URL ``$ref``s and inline nested objects.
This tool reads those ``attributes.yaml`` files directly, expands inline nested
objects into their own sub-tables, and renders the same column layout. A field's
``x-standard`` annotation (when present in the source) leads its Description cell
with "**Based on** <standard>." exactly as the sibling tool does.

The DEG repo is a *sibling* of this one; its location is configurable via
``--deg-repo`` (default ``../../DEG`` relative to this repo's root) or the
``DEG_REPO`` env var. The DEG sources are read-only here.

Usage:
  python3 scripts/generate_external_field_tables.py                 # write the page
  python3 scripts/generate_external_field_tables.py --check         # CI: fail if stale
  python3 scripts/generate_external_field_tables.py --schema-repo /abs/path/to/DEG
"""
from __future__ import annotations

import argparse
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "schemas", "external")
DASH = "—"
START = "<!-- FIELD-TABLE:START — auto-generated by scripts/generate_external_field_tables.py; do not edit by hand -->"
END = "<!-- FIELD-TABLE:END -->"
COL_RULE = "|----|-------|-----------------|"

VERSION = "v2.0"
# Canonical published location of each schema (its definition + JSON-LD context).
SCHEMA_BASE = "https://schema.beckn.io"
# Where the source attributes.yaml are read from (a local checkout of the repo
# that publishes to SCHEMA_BASE). Path is configurable via --schema-repo.
DEG_DEVKITS = "https://github.com/beckn/DEG/tree/main/devkits"
DEG_GUIDES = "https://github.com/beckn/DEG/tree/main/docs/implementation-guides/v2"

OUT_FILE = "README.md"  # single merged page under schemas/external/

# ---------------------------------------------------------------------------
# Schemas to document, grouped by domain into one section each on a single page.
# Shared item / contract / settlement primitives (EnergyResource, DEGContract,
# RevenueFlow) are documented once under Energy Trading; Demand Flex notes the
# reuse. Each entry is a schema folder name (resolved under <repo>/specification/
# schema/<name>/<VERSION>). `links` are rendered in the section header.
# ---------------------------------------------------------------------------
GROUPS = [
    {
        "title": "Energy Trading (P2P)",
        "links": [
            ("Use case", "../../use-cases/energy-trading/README.md"),
            ("Devkit", f"{DEG_DEVKITS}/p2p-trading-ies-wave2"),
        ],
        "intro": (
            "A peer-to-peer trade is modelled as a `P2PTrade` contract (a beckn "
            "`Contract` subclass) whose energy-specific attributes are carried by "
            "the offer, customer, order-item, settlement and resource schemas "
            "below. `EnergyResource`, `DEGContract` and `RevenueFlow` are shared "
            "primitives — Demand Flexibility reuses them."
        ),
        "schemas": [
            "P2PTrade",
            "EnergyTradeOffer",
            "EnergyCustomer",
            "EnergyOrderItem",
            "RevenueFlow",
            "DEGContract",
            "EnergyResource",
        ],
    },
    {
        "title": "Demand Flexibility",
        "links": [
            ("Guide", f"{DEG_GUIDES}/Demand_Flexibility"),
            ("Devkit", f"{DEG_DEVKITS}/demand-flex"),
        ],
        "intro": (
            "A flexibility programme advertises a `DemandFlexNeed`, contracts via "
            "a `DemandFlexBuyOffer`, and reports measurement & verification with "
            "`DemandFlexPerformance`. It reuses the shared `EnergyResource`, "
            "`DEGContract` and `RevenueFlow` schemas listed under Energy Trading."
        ),
        "schemas": [
            "DemandFlexNeed",
            "DemandFlexBuyOffer",
            "DemandFlexPerformance",
        ],
    },
]


# --------------------------------------------------------------------------- #
# Rendering helpers
# --------------------------------------------------------------------------- #
def collapse(text) -> str:
    return " ".join(str(text).split())


def md_escape(text: str) -> str:
    return str(text).replace("|", "\\|")


def code_enum(values) -> str:
    return " / ".join("`" + str(v) + "`" for v in values)


def ref_label(ref: str) -> str:
    """Human label for a $ref. Handles internal (#/components/schemas/X, #/$defs/X),
    fragment URLs (…/Schema/v1.0#/components/schemas/X) and whole-schema URLs
    (https://schema.beckn.io/EnergyContract/v2.0 -> 'EnergyContract')."""
    base, _, frag = ref.partition("#")
    if frag:
        return frag.rstrip("/").split("/")[-1]
    parts = [p for p in base.rstrip("/").split("/") if p]
    last = parts[-1]
    if re.match(r"^v?\d+(\.\d+)*$", last) and len(parts) >= 2:  # trailing version
        return parts[-2]
    return last


def single_ref(prop: dict):
    """If prop is (or wraps via a single-element allOf) one $ref, return it."""
    if prop.get("$ref"):
        return prop["$ref"]
    allof = prop.get("allOf")
    if isinstance(allof, list):
        refs = [a["$ref"] for a in allof if isinstance(a, dict) and "$ref" in a]
        if len(refs) == 1 and not prop.get("properties"):
            return refs[0]
    return None


def type_str(prop: dict) -> str:
    if not isinstance(prop, dict):
        return DASH
    ref = single_ref(prop)
    if ref:
        return ref_label(ref)
    if "enum" in prop:
        return code_enum(prop["enum"])
    for comb in ("oneOf", "anyOf"):
        if isinstance(prop.get(comb), list):
            labels, nullable = [], False
            for sub in prop[comb]:
                if isinstance(sub, dict) and sub.get("type") == "null":
                    nullable = True
                    continue
                labels.append(type_str(sub))
            uniq = []
            for lab in labels:
                if lab != DASH and lab not in uniq:
                    uniq.append(lab)
            base = " or ".join(uniq) if uniq else "object"
            return base + (" (nullable)" if nullable else "")
    t = prop.get("type")
    fmt = prop.get("format")
    if isinstance(t, list):
        nn = [x for x in t if x != "null"]
        base = " / ".join("text" if x == "string" else x for x in nn) if nn else "any"
        return base + (" (nullable)" if "null" in t else "")
    if t == "array":
        item = type_str(prop.get("items", {}))
        return "list of " + ("any" if item == DASH else item)
    if t == "string":
        return fmt or "text"
    if t == "boolean":
        return "yes / no"
    if t in ("integer", "number", "object"):
        return t
    return t or DASH


def desc_cell(prop: dict) -> str:
    parts = []
    std = prop.get("x-standard") if isinstance(prop, dict) else None
    if std:
        parts.append(f"**Based on** {md_escape(collapse(std))}.")
    d = prop.get("description") if isinstance(prop, dict) else None
    if d:
        parts.append(md_escape(collapse(d)))
    return " ".join(parts) or DASH


def inline_object(prop: dict):
    """Return (properties, required) when prop is an inline object with its own
    properties (so it warrants a sub-table), else None. Looks through a single
    array level (items) and through allOf members that carry inline properties."""
    if not isinstance(prop, dict):
        return None
    node = prop
    if prop.get("type") == "array" and isinstance(prop.get("items"), dict):
        node = prop["items"]
    # Skip pure $ref nodes (they resolve to a named schema documented elsewhere).
    if single_ref(node):
        return None
    props = dict(node.get("properties") or {})
    required = set(node.get("required") or [])
    for sub in node.get("allOf", []) if isinstance(node.get("allOf"), list) else []:
        if isinstance(sub, dict) and not sub.get("$ref"):
            props.update(sub.get("properties") or {})
            required |= set(sub.get("required") or [])
    if props:
        return props, sorted(required)
    return None


def resolve_component(comp: dict, schemas: dict):
    """Merge properties/required across allOf; expand only *internal* allOf refs.
    Returns (props, required, inherited_external_names)."""
    props: dict = {}
    required: set = set()
    inherited: list = []
    for sub in comp.get("allOf", []) if isinstance(comp.get("allOf"), list) else []:
        if isinstance(sub, dict) and "$ref" in sub:
            name = ref_label(sub["$ref"])
            if sub["$ref"].startswith("#") and name in schemas:
                p, r, inh = resolve_component(schemas[name], schemas)
                props.update(p)
                required |= set(r)
                inherited += inh
            else:
                inherited.append(name)
        elif isinstance(sub, dict):
            props.update(sub.get("properties") or {})
            required |= set(sub.get("required") or [])
    props.update(comp.get("properties") or {})
    required |= set(comp.get("required") or [])
    return props, sorted(required), inherited


def rows_for(props: dict, required) -> list:
    required = set(required)
    rows = []
    for name, prop in props.items():
        if name == "@context":
            continue
        field = f"**`{md_escape(name)}`** \\*" if name in required else f"`{md_escape(name)}`"
        rows.append((field, md_escape(type_str(prop)), desc_cell(prop)))
    return rows


def render_table(rows: list) -> str:
    out = ["| Field | Type | Description |", COL_RULE]
    out += [f"| {f} | {t} | {d} |" for f, t, d in rows]
    out.append("")
    return "\n".join(out)


def is_pure_alias(comp: dict) -> bool:
    """A component that is only a ``$ref`` to another (external) schema — these
    add no fields of their own, so we don't give them a section."""
    return (isinstance(comp, dict) and "$ref" in comp
            and not (comp.get("properties") or comp.get("allOf") or comp.get("oneOf")))


def emit_tables(root_title: str, props: dict, required) -> list[str]:
    """Primary table (no caption) followed by breadth-first captioned sub-tables
    for each inline nested object."""
    parts: list[str] = [render_table(rows_for(props, required))]
    queue = [(root_title, props)]
    while queue:
        parent, pprops = queue.pop(0)
        for pname, prop in pprops.items():
            if pname == "@context":
                continue
            nested = inline_object(prop)
            if not nested:
                continue
            arr = isinstance(prop, dict) and prop.get("type") == "array"
            title = f"{parent}.{pname}" + ("[]" if arr else "")
            sub_props, sub_req = nested
            rows = rows_for(sub_props, sub_req)
            if rows:
                parts.append(f"_Object: `{title}`_\n\n" + render_table(rows))
                queue.append((title, sub_props))
    return parts


def component_section(comp_name: str, comp: dict, schemas: dict, heading_level: int) -> list[str]:
    """Render a component as an optional heading + description + one or more
    tables. When the component declares no local properties (pure external allOf
    / oneOf union) emit an inheritance/union note instead of an empty table.
    ``heading_level`` of 0 suppresses the component heading (sole component)."""
    parts: list[str] = []
    if heading_level:
        parts += [f"{'#' * heading_level} {comp_name}", ""]
    if comp.get("deprecated"):
        parts += [f"> **Deprecated.** {collapse(comp.get('x-supersededBy', ''))}".rstrip(), ""]
    if comp.get("description"):
        parts += [collapse(comp["description"]), ""]

    props, required, inherited = resolve_component(comp, schemas)
    one_of = comp.get("oneOf")

    if not props:
        notes = []
        if inherited:
            notes.append("Inherits all fields from " + " → ".join(f"**{n}**" for n in inherited) + ".")
        if isinstance(one_of, list):
            kinds = [ref_label(s["$ref"]) for s in one_of if isinstance(s, dict) and "$ref" in s]
            if kinds:
                notes.append("Discriminated union (`oneOf`) of: " + ", ".join(f"`{k}`" for k in kinds) + ".")
        if not notes:
            notes.append("No directly-declared fields.")
        parts += ["_" + " ".join(notes) + "_", ""]
        return parts

    parts += emit_tables(comp_name, props, required)
    return parts


# --------------------------------------------------------------------------- #
# Page assembly
# --------------------------------------------------------------------------- #
def load_doc(repo: str, schema: str) -> dict:
    path = os.path.join(repo, "specification", "schema", schema, VERSION, "attributes.yaml")
    if not os.path.exists(path):
        raise FileNotFoundError(path)
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def schema_section(repo: str, schema: str) -> list[str]:
    """One schema's heading + source link + component table(s)."""
    doc = load_doc(repo, schema)
    schemas = doc.get("components", {}).get("schemas", {})
    src = f"[`{schema}/{VERSION}`]({SCHEMA_BASE}/{schema}/{VERSION})"
    out = [f"### {schema}", "",
           f"_Defined at {src} — {collapse(doc.get('info', {}).get('title', schema))}._", ""]
    # The named component matching the folder first, then any siblings;
    # pure-alias stubs (a bare $ref to an external schema) are skipped.
    ordered = ([schema] if schema in schemas else []) + [n for n in schemas if n != schema]
    documented = [n for n in ordered if not is_pure_alias(schemas[n])]
    # When the schema is a single same-named component, don't repeat the name;
    # otherwise give each component its own H4.
    solo = len(documented) == 1 and documented[0] == schema
    for comp_name in documented:
        out += component_section(comp_name, schemas[comp_name], schemas, heading_level=0 if solo else 4)
    return out


def build_page(repo: str) -> str:
    parts = [
        "# External Schemas",
        "",
        "Some schemas used across IES are **defined and published outside this "
        f"repository** — served canonically at [schema.beckn.io]({SCHEMA_BASE}) — "
        "and documented here so the book carries a complete field reference. Each "
        "schema links to its canonical definition; each domain links to its "
        "use-case guide and deployable devkit.",
        "",
        "{% hint style=\"info\" %}",
        "These tables are **auto-generated** from the schema sources by "
        f"`scripts/generate_external_field_tables.py` (version `{VERSION}`). Don't "
        "edit by hand — re-run the generator to refresh. Where a field derives "
        "from a recognised standard, its description begins with **Based on** and "
        "the standard reference (from the source's `x-standard` annotation).",
        "{% endhint %}",
        "",
    ]
    for group in GROUPS:
        links = " · ".join(f"[{label}]({url})" for label, url in group.get("links", []))
        parts += [f"## {group['title']}", ""]
        if links:
            parts += [f"**{links}**", ""]
        parts += [group["intro"], "", START, ""]
        for schema in group["schemas"]:
            parts += schema_section(repo, schema)
        parts += [END, ""]
    return "\n".join(parts).rstrip() + "\n"


def write_or_check(path: str, content: str, check: bool) -> bool:
    current = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            current = f.read()
    if current == content:
        print(f"unchanged: {os.path.relpath(path, ROOT)}")
        return True
    if check:
        print(f"STALE: {os.path.relpath(path, ROOT)} (run without --check to update)")
        return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"{'wrote':>9}: {os.path.relpath(path, ROOT)}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    default_repo = os.environ.get("SCHEMA_REPO", os.environ.get("DEG_REPO", os.path.join(ROOT, "..", "..", "DEG")))
    ap.add_argument("--schema-repo", "--deg-repo", dest="schema_repo", default=default_repo,
                    help="local checkout that holds the schema sources "
                         "(default: ../../DEG, or $SCHEMA_REPO / $DEG_REPO)")
    ap.add_argument("--check", action="store_true", help="exit non-zero if the page is stale (no writes)")
    args = ap.parse_args()

    repo = os.path.abspath(args.schema_repo)
    if not os.path.isdir(os.path.join(repo, "specification", "schema")):
        ap.error(f"schema sources not found at {repo} (pass --schema-repo or set SCHEMA_REPO)")

    ok = write_or_check(os.path.join(OUT_DIR, OUT_FILE), build_page(repo), args.check)
    # Remove the superseded per-domain pages from the earlier multi-page layout.
    for stale in ("energy-trading.md", "demand-flex.md"):
        p = os.path.join(OUT_DIR, stale)
        if os.path.exists(p) and not args.check:
            os.remove(p)
            print(f"{'removed':>9}: {os.path.relpath(p, ROOT)}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
