#!/usr/bin/env python3
"""Generate the developer-facing ``schemas-ies/`` section — a schema.beckn.io-style
catalog and one term page per schema family.

For each family ``schemas/<Family>/`` this produces ``schemas-ies/<Family>.md``:

  * title + tagline + at-a-glance (canonical base URL, latest version, status)
  * a **Developer resources** table for the current version — the canonical
    ``https://india-energy-stack.github.io/ies-accelerator/schemas/<Family>/<ver>/…``
    URLs that resolve at runtime (schemas/ is served verbatim by GitHub Pages)
  * the current version's field reference, inline
  * every previous version below, each in a collapsible <details> with its own
    developer-resource table and field tables

and ``schemas-ies/README.md`` — the searchable catalog listing every family,
grouped by category, each linking to its page.

The field tables are built from the compiled ``schema.json`` in each version dir,
reusing the primitives in ``generate_field_tables.py`` so the two stay consistent.
Family-level metadata (category, use-case links) that is not in schema.json lives
in FAMILIES below; the tagline and status line are parsed from each family README.

Nothing here moves or copies the raw schema files — this is a presentation layer
that links to the canonical files under ``schemas/``.

Usage:
  python3 scripts/generate_schemas_ies.py            # regenerate the whole section
  python3 scripts/generate_schemas_ies.py --check    # CI: fail if anything is stale
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

# Reuse the field-table primitives (same repo, no package) so the developer
# section and the per-version README field references never diverge.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import generate_field_tables as gft  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMAS_DIR = os.path.join(ROOT, "schemas")
OUT_DIR = os.path.join(ROOT, "schemas-ies")

PAGES_BASE = "https://india-energy-stack.github.io/ies-accelerator/schemas"
REPO_TREE = "https://github.com/India-Energy-Stack/ies-accelerator/tree/main/schemas"

AUTOGEN = "<!-- AUTO-GENERATED by scripts/generate_schemas_ies.py — do not edit by hand -->"

# Category + use-case wiring that is not derivable from schema.json. Order within
# a category is the catalog order. `used` links are relative to a schemas-ies/ page.
FAMILIES: dict[str, dict] = {
    "ElectricityCredential": {
        "category": "Verifiable Credentials",
        "used": "[Consumer Energy Passport](../use-cases/consumer-energy-passport/README.md) · "
                "[DER Visibility](../use-cases/der-visibility/README.md)",
    },
    "MeterDataCredential": {
        "category": "Verifiable Credentials",
        "used": "[Consumer Meter Digest](../use-cases/consumer-meter-digest/README.md)",
    },
    "MeterDataRequestCredential": {
        "category": "Verifiable Credentials",
        "used": "[Smart Meter Data Exchange](../use-cases/smart-meter-data-exchange/README.md) (optional consent proof)",
    },
    "MeterData": {
        "category": "Data Exchange payloads",
        "used": "[Smart Meter Data Exchange](../use-cases/smart-meter-data-exchange/README.md) · "
                "[Consumer Meter Digest](../use-cases/consumer-meter-digest/README.md)",
    },
    "MeterDataRequest": {
        "category": "Data Exchange payloads",
        "used": "[Smart Meter Data Exchange](../use-cases/smart-meter-data-exchange/README.md)",
    },
    "ArrFiling": {
        "category": "Data Exchange payloads",
        "used": "[DISCOM Regulatory Filing](../use-cases/discom-regulatory-filing/README.md)",
    },
    "OutageNotification": {
        "category": "Data Exchange payloads",
        "used": "— no IES use-case guide yet",
    },
}

CATEGORY_ORDER = ["Verifiable Credentials", "Data Exchange payloads"]
CATEGORY_BLURB = {
    "Verifiable Credentials": "W3C VC payloads — signed, durable records the holder keeps and "
                              "verifies independently of any network.",
    "Data Exchange payloads": "Structured, non-credential payloads exchanged over the network or "
                              "published as feeds.",
}

# Raw asset files a version dir may carry, in developer-table order.
ASSET_FILES = [
    ("attributes.yaml", "OpenAPI 3.1 source of truth"),
    ("schema.json", "compiled JSON Schema (Draft 2020-12) — validate against this"),
    ("context.jsonld", "JSON-LD context for semantic resolution"),
    ("vocab.jsonld", "RDF vocabulary with standards alignments"),
]


def _h(s: str) -> str:
    """Minimal HTML escape for text placed inside the catalog cards."""
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def cards_table(families: list[str]) -> str:
    """A grid of clickable cards — one per family — using GitBook's native
    ``<table data-view="cards">`` block. GitBook renders it as a responsive card
    grid (name → version → description, whole card links to the family page); any
    other renderer degrades it to a plain table, so it never breaks."""
    head = ('<table data-view="cards"><thead><tr>'
            '<th></th><th></th><th></th>'
            '<th data-hidden data-card-target data-type="content-ref"></th>'
            '</tr></thead><tbody>')
    rows = [head]
    for f in families:
        info = parse_readme(f)
        latest = versions_of(f)[0]
        desc = _h(info["tagline"] or "")
        rows.append(
            f'<tr><td><strong>{f}</strong></td><td>{_h(latest)}</td><td>{desc}</td>'
            f'<td><a href="{f}.md">{f}.md</a></td></tr>'
        )
    rows.append("</tbody></table>")
    return "\n".join(rows)


def version_key(v: str) -> tuple:
    """Sort key for a 'v1.2' / 'v0.10' style dir name — numeric, newest first."""
    nums = re.findall(r"\d+", v)
    return tuple(int(n) for n in nums) if nums else (0,)


def versions_of(family: str) -> list[str]:
    """Version dir names (e.g. ['v1.2','v1.1','v1.0']) that carry a schema.json,
    newest first."""
    fam_dir = os.path.join(SCHEMAS_DIR, family)
    vers = [
        d for d in os.listdir(fam_dir)
        if d.startswith("v")
        and os.path.isdir(os.path.join(fam_dir, d))
        and os.path.exists(os.path.join(fam_dir, d, "schema.json"))
    ]
    return sorted(vers, key=version_key, reverse=True)


def parse_readme(family: str) -> dict:
    """Pull the tagline (single-asterisk italic line), the Status line, and any
    WIP warning from a family README."""
    path = os.path.join(SCHEMAS_DIR, family, "README.md")
    tagline, status, wip = "", "", False
    if not os.path.exists(path):
        return {"tagline": tagline, "status": status, "wip": wip}
    with open(path, encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not tagline:
                m = re.match(r"^\*([^*].*[^*])\*$", s)
                if m:
                    tagline = m.group(1).strip()
            if not status and s.startswith("**Status:**"):
                status = s[len("**Status:**"):].strip()
            if "WORK IN PROGRESS" in s.upper():
                wip = True
    return {"tagline": tagline, "status": status, "wip": wip}


# ---- field tables -----------------------------------------------------------

def _component_table(title: str, comp: dict, defs: dict, bold_label: bool) -> str:
    props, required = gft.resolve(comp, defs)
    rows = []
    for name, prop in props.items():
        if name == "@context":
            continue
        field = f"**`{gft.md_escape(name)}`** \\*" if name in required else f"`{gft.md_escape(name)}`"
        standard = prop.get("x-standard") if isinstance(prop, dict) else None
        desc = gft.md_escape(gft.desc_str(prop))
        parts = []
        if standard:
            parts.append(f"**Based on** {gft.md_escape(standard)}.")
        if desc != gft.DASH:
            parts.append(desc)
        rows.append((field, gft.md_escape(gft.type_str(prop, defs)), " ".join(parts) or gft.DASH))
    if not rows:
        return ""
    # Current version uses ### headings (they surface in the page TOC); previous
    # versions use bold labels so the collapsed tables don't clutter the TOC.
    head = f"**{title}**" if bold_label else f"### {title}"
    lines = [head, "", "| Field | Type | Description |", "|---|---|---|"]
    lines += [f"| {f} | {t} | {d} |" for f, t, d in rows]
    lines.append("")
    return "\n".join(lines)


def field_tables(schema: dict, bold_label: bool = False) -> str:
    """One table per object component: the root payload (if it has properties)
    then each $defs entry."""
    defs = schema.get("$defs", {})
    parts = []
    if schema.get("properties"):
        parts.append(_component_table(schema.get("title", "Payload"), schema, defs, bold_label))
    for name, comp in defs.items():
        if isinstance(comp, dict) and ("properties" in comp or "allOf" in comp):
            t = _component_table(comp.get("title", name), comp, defs, bold_label)
            if t:
                parts.append(t)
    return "\n".join(p for p in parts if p)


# ---- developer resources ----------------------------------------------------

def dev_resources_table(family: str, ver: str) -> str:
    base = f"{PAGES_BASE}/{family}/{ver}"
    ver_dir = os.path.join(SCHEMAS_DIR, family, ver)
    rows = [("Field reference (README)", f"{base}/README.md", "human-readable field reference for this version")]
    for fname, note in ASSET_FILES:
        if os.path.exists(os.path.join(ver_dir, fname)):
            rows.append((f"`{fname}`", f"{base}/{fname}", note))
    if os.path.isdir(os.path.join(ver_dir, "examples")):
        rows.append(("`examples/`", f"{REPO_TREE}/{family}/{ver}/examples", "worked payloads"))
    out = ["| Resource | URL | Notes |", "|---|---|---|"]
    for label, url, note in rows:
        out.append(f"| {label} | [{url}]({url}) | {note} |")
    return "\n".join(out)


# ---- page assembly ----------------------------------------------------------

def family_page(family: str) -> str:
    meta = FAMILIES[family]
    info = parse_readme(family)
    vers = versions_of(family)
    latest = vers[0]
    olders = vers[1:]

    schema_path = os.path.join(SCHEMAS_DIR, family, latest, "schema.json")
    with open(schema_path, encoding="utf-8") as f:
        latest_schema = json.load(f)

    L: list[str] = [AUTOGEN, "", f"# {family}", ""]
    if info["tagline"]:
        L += [f"*{info['tagline']}*", ""]
    if info["wip"]:
        L += ["> ⚠️ **Work in progress — subject to change.** Field names, enums and interpretation "
              "are not final. Do not depend on it for production integrations yet.", ""]

    # At-a-glance
    L += ["| | |", "|---|---|"]
    L.append(f"| **Canonical base** | `{PAGES_BASE}/{family}` |")
    L.append(f"| **Latest version** | **{latest}** |")
    L.append(f"| **All versions** | {', '.join(vers)} |")
    if info["status"]:
        L.append(f"| **Status** | {info['status']} |")
    L.append(f"| **Category** | {meta['category']} |")
    L.append(f"| **Used in** | {meta['used']} |")
    L.append("")

    L += ["See the full family notes — inheritance, standards basis, design rationale — in "
          f"[{family} (schemas)](../schemas/{family}/README.md).", ""]

    # Current version
    L += [f"## Developer resources — {latest} (current)", "", dev_resources_table(family, latest), ""]
    L += [f"## Field reference — {latest} (current)", "",
          "_A field name in **bold** with a trailing **\\*** is required; all others are optional. "
          "**Type** shows units for QuantitativeValue models. Where a field derives from a standard, "
          "its description begins with **Based on** and the standard reference._", ""]
    L += [field_tables(latest_schema, bold_label=True), ""]

    # Previous versions
    L += ["---", "", "## Previous versions", ""]
    if not olders:
        L += [f"_{latest} is the first published version — no previous versions yet._", ""]
    else:
        L += ["> Older versions stay published and reachable at their canonical URLs. "
              "Clients pin a version explicitly.", ""]
        for v in olders:
            with open(os.path.join(SCHEMAS_DIR, family, v, "schema.json"), encoding="utf-8") as f:
                sch = json.load(f)
            L += [f"<details>", f"<summary><b>{v}</b> — field reference &amp; files</summary>", ""]
            L += [f"[Field reference (README)]({PAGES_BASE}/{family}/{v}/README.md) · in this book: "
                  f"[{family} {v}](../schemas/{family}/{v}/README.md)", ""]
            L += [dev_resources_table(family, v), ""]
            L += [field_tables(sch, bold_label=True), ""]
            L += ["</details>", ""]

    return "\n".join(L).rstrip() + "\n"


def catalog_page() -> str:
    L: list[str] = [
        AUTOGEN, "",
        "# IES Schemas",
        "",
        "> **The developer catalog of every IES schema.** Pick a schema below — each has its own page "
        "with the current field reference, the canonical file URLs, and every previous version. "
        "Use the search box (top) to find a schema or field across all of them.",
        "",
    ]
    for cat in CATEGORY_ORDER:
        fams = [f for f, m in FAMILIES.items() if m["category"] == cat]
        if not fams:
            continue
        L += [f"## {cat}", "", CATEGORY_BLURB[cat], "", cards_table(fams), ""]

    L += [
        "## External — DEG schemas IES uses",
        "",
        "Schemas defined and published outside this repository, canonical at "
        "[schema.beckn.io](https://schema.beckn.io). Their field reference is mirrored in "
        "[External Schemas](../schemas/external/README.md).",
        "",
        "---",
        "",
        "## How versions work",
        "",
        "Every schema lives at `schemas/<Family>/v<version>/` with its own `attributes.yaml` (source "
        "of truth), compiled `schema.json`, `context.jsonld`, `vocab.jsonld`, `examples/` and a "
        "generated `README.md` field reference. A **non-breaking** change (additive, optional fields, "
        "new enum values) is absorbed by the same minor version; a **breaking** change (rename, "
        "removal, type or semantics change) is published in a new sibling version, never overwriting "
        "the old one. Old versions stay reachable — see **Previous versions** on each page.",
        "",
        "To propose a new schema or a change, see the [proposal flow](../schemas/README.md#proposing-a-new-schema-or-a-change).",
    ]
    return "\n".join(L).rstrip() + "\n"


def build() -> dict[str, str]:
    """Return {abs_path: content} for every file this generator owns."""
    files = {os.path.join(OUT_DIR, "README.md"): catalog_page()}
    for family in FAMILIES:
        files[os.path.join(OUT_DIR, f"{family}.md")] = family_page(family)
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit non-zero if any file is stale (no writes)")
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    files = build()
    stale = False
    for path, content in files.items():
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        rel = os.path.relpath(path, ROOT)
        if current == content:
            print(f"unchanged: {rel}")
            continue
        stale = True
        if args.check:
            print(f"STALE: {rel} (run without --check to update)")
            continue
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"updated:   {rel}")
    if args.check and stale:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
