#!/usr/bin/env python3
"""Generate Field / Type / Description reference pages for **external** schemas
that live in a sibling DEG repo, and embed them as GitBook/PDF pages in this repo.

Why this exists
---------------
The IES Accelerator book (GitBook + the `build_pdf.sh` PDF) is built entirely
from the Markdown files listed in ``SUMMARY.md``. To surface schemas that are
authored in another repository (the DEG monorepo: Energy Trading / P2P wave2 and
Demand Flexibility), we generate self-contained Markdown pages here from those
schemas' source and list them in ``SUMMARY.md``. GitBook renders them like any
other page; ``scripts/build_pdf.py`` concatenates them and even shrinks the
generated tables (it keys on the same ``<!-- FIELD-TABLE -->`` markers used by
``scripts/generate_field_tables.py``).

Difference from ``generate_field_tables.py``
--------------------------------------------
That sibling tool reads a *compiled* ``schema.json`` (a flat ``$defs`` map). The
DEG trading / demand-flex schemas have no ``schema.json`` — they are authored as
OpenAPI ``attributes.yaml`` (``components.schemas``) with ``allOf`` inheritance,
internal ``$defs``, ``schema.beckn.io`` URL ``$ref``s and inline nested objects.
This tool reads those ``attributes.yaml`` files directly, expands inline nested
objects into their own sub-tables, and renders the same column layout. A field's
``x-standard`` annotation (when present in the source) leads its Description cell
with "**Based on** <standard>." exactly as the sibling tool does.

The DEG repo is a *sibling* of this one; its location is configurable via
``--deg-repo`` (default ``../../DEG`` relative to this repo's root) or the
``DEG_REPO`` env var. The DEG sources are read-only here.

Usage:
  python3 scripts/generate_external_field_tables.py            # write pages
  python3 scripts/generate_external_field_tables.py --check    # CI: fail if stale
  python3 scripts/generate_external_field_tables.py --deg-repo /abs/path/to/DEG
"""
from __future__ import annotations

import argparse
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "schemas", "external")
DASH = "—"
START = "<!-- FIELD-TABLE:START — auto-generated by scripts/generate_external_field_tables.py from the DEG repo; do not edit by hand -->"
END = "<!-- FIELD-TABLE:END -->"
COL_RULE = "|----|-------|-----------------|"

VERSION = "v2.0"
DEG_SCHEMA_BASE = ("https://github.com/India-Energy-Stack/DEG/tree/main/"
                   "specification/schema")

# ---------------------------------------------------------------------------
# Which DEG schemas to document, grouped into one page each. The shared item /
# contract / settlement primitives (EnergyResource, DEGContract, RevenueFlow)
# are documented once under Energy Trading; Demand Flex cross-references them.
# Each entry: schema folder name under DEG specification/schema/<name>/<VERSION>.
# ---------------------------------------------------------------------------
GROUPS = [
    {
        "slug": "energy-trading",
        "title": "Energy Trading (P2P, wave2)",
        "devkit": "devkits/p2p-trading-ies-wave2",
        "intro": (
            "Field reference for the schemas used by the **P2P energy-trading "
            "(wave2)** devkit in the DEG repo. A P2P trade is modelled as a "
            "`P2PTrade` contract (a beckn `Contract` subclass) whose energy-"
            "specific attributes are carried by the offer, customer, order-item, "
            "settlement and resource schemas below.\n\n"
            "`EnergyResource`, `DEGContract` and `RevenueFlow` are shared "
            "primitives — Demand Flexibility reuses them."
        ),
        "schemas": [
            "P2PTrade",
            "EnergyTradeOffer",
            "EnergyCustomer",
            "EnergyOrderItem",
            "RevenueFlow",
            "DEGContract",
            "EnergyResource",
        ],
    },
    {
        "slug": "demand-flex",
        "title": "Demand Flexibility",
        "devkit": "devkits/demand-flex",
        "intro": (
            "Field reference for the schemas used by the **demand-flex** devkit "
            "in the DEG repo. A flex programme advertises a `DemandFlexNeed`, "
            "contracts via a `DemandFlexBuyOffer`, and reports measurement & "
            "verification with `DemandFlexPerformance`.\n\n"
            "Demand Flex also reuses the shared `EnergyResource`, `DEGContract` "
            "and `RevenueFlow` schemas documented under "
            "[Energy Trading](energy-trading.md)."
        ),
        "schemas": [
            "DemandFlexNeed",
            "DemandFlexBuyOffer",
            "DemandFlexPerformance",
        ],
    },
]


# --------------------------------------------------------------------------- #
# Rendering helpers
# --------------------------------------------------------------------------- #
def collapse(text) -> str:
    return " ".join(str(text).split())


def md_escape(text: str) -> str:
    return str(text).replace("|", "\\|")


def code_enum(values) -> str:
    return " / ".join("`" + str(v) + "`" for v in values)


def ref_label(ref: str) -> str:
    """Human label for a $ref. Handles internal (#/components/schemas/X, #/$defs/X),
    fragment URLs (…/Schema/v1.0#/components/schemas/X) and whole-schema URLs
    (https://schema.beckn.io/EnergyContract/v2.0 -> 'EnergyContract')."""
    base, _, frag = ref.partition("#")
    if frag:
        return frag.rstrip("/").split("/")[-1]
    parts = [p for p in base.rstrip("/").split("/") if p]
    last = parts[-1]
    if re.match(r"^v?\d+(\.\d+)*$", last) and len(parts) >= 2:  # trailing version
        return parts[-2]
    return last


def single_ref(prop: dict):
    """If prop is (or wraps via a single-element allOf) one $ref, return it."""
    if prop.get("$ref"):
        return prop["$ref"]
    allof = prop.get("allOf")
    if isinstance(allof, list):
        refs = [a["$ref"] for a in allof if isinstance(a, dict) and "$ref" in a]
        if len(refs) == 1 and not prop.get("properties"):
            return refs[0]
    return None


def type_str(prop: dict) -> str:
    if not isinstance(prop, dict):
        return DASH
    ref = single_ref(prop)
    if ref:
        return ref_label(ref)
    if "enum" in prop:
        return code_enum(prop["enum"])
    for comb in ("oneOf", "anyOf"):
        if isinstance(prop.get(comb), list):
            labels, nullable = [], False
            for sub in prop[comb]:
                if isinstance(sub, dict) and sub.get("type") == "null":
                    nullable = True
                    continue
                labels.append(type_str(sub))
            uniq = []
            for lab in labels:
                if lab != DASH and lab not in uniq:
                    uniq.append(lab)
            base = " or ".join(uniq) if uniq else "object"
            return base + (" (nullable)" if nullable else "")
    t = prop.get("type")
    fmt = prop.get("format")
    if isinstance(t, list):
        nn = [x for x in t if x != "null"]
        base = " / ".join("text" if x == "string" else x for x in nn) if nn else "any"
        return base + (" (nullable)" if "null" in t else "")
    if t == "array":
        item = type_str(prop.get("items", {}))
        return "list of " + ("any" if item == DASH else item)
    if t == "string":
        return fmt or "text"
    if t == "boolean":
        return "yes / no"
    if t in ("integer", "number", "object"):
        return t
    return t or DASH


def desc_cell(prop: dict) -> str:
    parts = []
    std = prop.get("x-standard") if isinstance(prop, dict) else None
    if std:
        parts.append(f"**Based on** {md_escape(collapse(std))}.")
    d = prop.get("description") if isinstance(prop, dict) else None
    if d:
        parts.append(md_escape(collapse(d)))
    return " ".join(parts) or DASH


def inline_object(prop: dict):
    """Return (properties, required) when prop is an inline object with its own
    properties (so it warrants a sub-table), else None. Looks through a single
    array level (items) and through allOf members that carry inline properties."""
    if not isinstance(prop, dict):
        return None
    node = prop
    if prop.get("type") == "array" and isinstance(prop.get("items"), dict):
        node = prop["items"]
    # Skip pure $ref nodes (they resolve to a named schema documented elsewhere).
    if single_ref(node):
        return None
    props = dict(node.get("properties") or {})
    required = set(node.get("required") or [])
    for sub in node.get("allOf", []) if isinstance(node.get("allOf"), list) else []:
        if isinstance(sub, dict) and not sub.get("$ref"):
            props.update(sub.get("properties") or {})
            required |= set(sub.get("required") or [])
    if props:
        return props, sorted(required)
    return None


def resolve_component(comp: dict, schemas: dict):
    """Merge properties/required across allOf; expand only *internal* allOf refs.
    Returns (props, required, inherited_external_names)."""
    props: dict = {}
    required: set = set()
    inherited: list = []
    for sub in comp.get("allOf", []) if isinstance(comp.get("allOf"), list) else []:
        if isinstance(sub, dict) and "$ref" in sub:
            name = ref_label(sub["$ref"])
            if sub["$ref"].startswith("#") and name in schemas:
                p, r, inh = resolve_component(schemas[name], schemas)
                props.update(p)
                required |= set(r)
                inherited += inh
            else:
                inherited.append(name)
        elif isinstance(sub, dict):
            props.update(sub.get("properties") or {})
            required |= set(sub.get("required") or [])
    props.update(comp.get("properties") or {})
    required |= set(comp.get("required") or [])
    return props, sorted(required), inherited


def rows_for(props: dict, required) -> list:
    required = set(required)
    rows = []
    for name, prop in props.items():
        if name == "@context":
            continue
        field = f"**`{md_escape(name)}`** \\*" if name in required else f"`{md_escape(name)}`"
        rows.append((field, md_escape(type_str(prop)), desc_cell(prop)))
    return rows


def render_table(rows: list) -> str:
    out = ["| Field | Type | Description |", COL_RULE]
    out += [f"| {f} | {t} | {d} |" for f, t, d in rows]
    out.append("")
    return "\n".join(out)


def is_pure_alias(comp: dict) -> bool:
    """A component that is only a ``$ref`` to another (external) schema — these
    add no fields of their own, so we don't give them a section."""
    return (isinstance(comp, dict) and "$ref" in comp
            and not (comp.get("properties") or comp.get("allOf") or comp.get("oneOf")))


def emit_tables(root_title: str, props: dict, required) -> list[str]:
    """Primary table (no caption) followed by breadth-first captioned sub-tables
    for each inline nested object."""
    parts: list[str] = [render_table(rows_for(props, required))]
    queue = [(root_title, props)]
    while queue:
        parent, pprops = queue.pop(0)
        for pname, prop in pprops.items():
            if pname == "@context":
                continue
            nested = inline_object(prop)
            if not nested:
                continue
            arr = isinstance(prop, dict) and prop.get("type") == "array"
            title = f"{parent}.{pname}" + ("[]" if arr else "")
            sub_props, sub_req = nested
            rows = rows_for(sub_props, sub_req)
            if rows:
                parts.append(f"_Object: `{title}`_\n\n" + render_table(rows))
                queue.append((title, sub_props))
    return parts


def component_section(comp_name: str, comp: dict, schemas: dict, heading: bool) -> list[str]:
    """Render a component as an optional heading + description + one or more
    tables. When the component declares no local properties (pure external allOf
    / oneOf union) emit an inheritance/union note instead of an empty table."""
    parts: list[str] = []
    if heading:
        parts += [f"### {comp_name}", ""]
    if comp.get("deprecated"):
        parts += [f"> **Deprecated.** {collapse(comp.get('x-supersededBy', ''))}".rstrip(), ""]
    if comp.get("description"):
        parts += [collapse(comp["description"]), ""]

    props, required, inherited = resolve_component(comp, schemas)
    one_of = comp.get("oneOf")

    if not props:
        notes = []
        if inherited:
            notes.append("Inherits all fields from " + " → ".join(f"**{n}**" for n in inherited) + ".")
        if isinstance(one_of, list):
            kinds = [ref_label(s["$ref"]) for s in one_of if isinstance(s, dict) and "$ref" in s]
            if kinds:
                notes.append("Discriminated union (`oneOf`) of: " + ", ".join(f"`{k}`" for k in kinds) + ".")
        if not notes:
            notes.append("No directly-declared fields.")
        parts += ["_" + " ".join(notes) + "_", ""]
        return parts

    parts += emit_tables(comp_name, props, required)
    return parts


# --------------------------------------------------------------------------- #
# Page assembly
# --------------------------------------------------------------------------- #
def load_doc(deg_repo: str, schema: str) -> dict:
    path = os.path.join(deg_repo, "specification", "schema", schema, VERSION, "attributes.yaml")
    if not os.path.exists(path):
        raise FileNotFoundError(path)
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_page(group: dict, deg_repo: str) -> str:
    head = [
        f"# {group['title']} schemas",
        "",
        group["intro"],
        "",
        "{% hint style=\"info\" %}",
        f"These tables are **auto-generated from the DEG repo** "
        f"(`{group['devkit']}` devkit, schema version `{VERSION}`) by "
        "`scripts/generate_external_field_tables.py`. Do not edit by hand — "
        "re-run the generator to refresh. The DEG schemas are the source of truth.",
        "{% endhint %}",
        "",
    ]
    body = [START, ""]
    for schema in group["schemas"]:
        doc = load_doc(deg_repo, schema)
        schemas = doc.get("components", {}).get("schemas", {})
        src = f"[`{schema}/{VERSION}`]({DEG_SCHEMA_BASE}/{schema}/{VERSION})"
        body.append(f"## {schema}")
        body.append("")
        body.append(f"_Source: {src} — {collapse(doc.get('info', {}).get('title', schema))}._")
        body.append("")
        # The named component matching the folder first, then any siblings;
        # pure-alias stubs (a bare $ref to an external schema) are skipped.
        ordered = ([schema] if schema in schemas else []) + [n for n in schemas if n != schema]
        documented = [n for n in ordered if not is_pure_alias(schemas[n])]
        # Don't repeat the schema name as an H3 when it is the sole component.
        solo = len(documented) == 1 and documented[0] == schema
        for comp_name in documented:
            body += component_section(comp_name, schemas[comp_name], schemas, heading=not solo)
    body.append(END)
    return "\n".join(head + body).rstrip() + "\n"


def build_index() -> str:
    rows = []
    for g in GROUPS:
        rows.append(
            f"| [{g['title']}]({g['slug']}.md) | `{g['devkit']}` | "
            + ", ".join(f"`{s}`" for s in g["schemas"]) + " |"
        )
    return "\n".join([
        "# External Schemas (DEG)",
        "",
        "Field references for schemas that are **authored in the "
        "[DEG repo](https://github.com/India-Energy-Stack/DEG)**, not in this "
        "repository. They are surfaced here so the GitBook and the printed PDF "
        "carry a complete field reference for the deployable DEG devkits without "
        "leaving the accelerator book.",
        "",
        "## Provenance",
        "",
        "These pages are **generated**, not hand-written. "
        "`scripts/generate_external_field_tables.py` reads each schema's "
        f"`attributes.yaml` from the DEG repo (version `{VERSION}`) and renders "
        "the same Field / Type / Description tables used elsewhere in this book. "
        "DEG is the source of truth; if a table looks stale, re-run the generator "
        "against the current DEG checkout (`--deg-repo /path/to/DEG`). Where a "
        "field derives from a recognised standard, its description begins with "
        "**Based on** and the standard reference (from the source's `x-standard` "
        "annotation).",
        "",
        "## Pages",
        "",
        "| Domain | DEG devkit | Schemas |",
        "|--------|-----------|---------|",
        *rows,
        "",
    ]) + "\n"


def write_or_check(path: str, content: str, check: bool) -> bool:
    current = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            current = f.read()
    if current == content:
        print(f"unchanged: {os.path.relpath(path, ROOT)}")
        return True
    if check:
        print(f"STALE: {os.path.relpath(path, ROOT)} (run without --check to update)")
        return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"{'wrote':>9}: {os.path.relpath(path, ROOT)}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--deg-repo", default=os.environ.get("DEG_REPO", os.path.join(ROOT, "..", "..", "DEG")),
                    help="path to the sibling DEG repo (default: ../../DEG or $DEG_REPO)")
    ap.add_argument("--check", action="store_true", help="exit non-zero if any page is stale (no writes)")
    args = ap.parse_args()

    deg_repo = os.path.abspath(args.deg_repo)
    if not os.path.isdir(os.path.join(deg_repo, "specification", "schema")):
        ap.error(f"DEG repo not found at {deg_repo} (pass --deg-repo or set DEG_REPO)")

    ok = write_or_check(os.path.join(OUT_DIR, "README.md"), build_index(), args.check)
    for group in GROUPS:
        page = build_page(group, deg_repo)
        ok &= write_or_check(os.path.join(OUT_DIR, f"{group['slug']}.md"), page, args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
