#!/usr/bin/env python3
"""Generate the developer-facing ``schemas-ies/`` section — a schema.nfh.global-style
catalog and one term page per schema family.

For each family ``schemas/<Family>/`` this produces ``schemas-ies/<Family>.md``:

  * title + tagline + at-a-glance (canonical base URL, current version, status)
  * a pointer to the plain-language page in ``what-ies-provides/schemas-overview/``
  * a **Developer resources** table for the current version — the canonical
    ``https://india-energy-stack.github.io/ies-accelerator/schemas/<Family>/<ver>/…``
    URLs that resolve at runtime (schemas/ is served verbatim by GitHub Pages)
  * the current version's field reference, inline
  * a **Versions** table listing every published version (newest first), each
    row linking to the in-book per-version page (``schemas/<Family>/<ver>/README.md``,
    a nav child of the family page) plus its raw-asset URLs; status and notes
    come from the family README's own Versions table

and ``schemas-ies/README.md`` — the searchable catalog listing every family,
grouped by category, each linking to its page.

The field tables are built from the compiled ``schema.json`` in each version dir,
reusing the primitives in ``generate_field_tables.py`` so the two stay consistent.
Family-level metadata (category, use-case links) that is not in schema.json lives
in FAMILIES below; the tagline and status line are parsed from each family README.

Nothing here moves or copies the raw schema files — this is a presentation layer
that links to the canonical files under ``schemas/``.

Usage:
  python3 scripts/generate_schemas_ies.py            # regenerate the whole section
  python3 scripts/generate_schemas_ies.py --check    # CI: fail if anything is stale
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

# Reuse the field-table primitives (same repo, no package) so the developer
# section and the per-version README field references never diverge.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import generate_field_tables as gft  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMAS_DIR = os.path.join(ROOT, "schemas")
OUT_DIR = os.path.join(ROOT, "schemas-ies")

PAGES_BASE = "https://india-energy-stack.github.io/ies-accelerator/schemas"
REPO_TREE = "https://github.com/India-Energy-Stack/ies-accelerator/tree/main/schemas"
REPO_BLOB = "https://github.com/India-Energy-Stack/ies-accelerator/blob/main/schemas"

# Plain-language companion pages (in-nav "Schemas Overview" section).
OVERVIEW_DIR = "../what-ies-provides/schemas-overview"

AUTOGEN = "<!-- AUTO-GENERATED by scripts/generate_schemas_ies.py — do not edit by hand -->"

# GitBook page front matter: hide the right-hand "On this page" outline for this
# section (the field references are long; the left nav already lists the pages).
FRONTMATTER = "---\nlayout:\n  outline:\n    visible: false\n---"

# Category + use-case wiring that is not derivable from schema.json. Order within
# a category is the catalog order. `used` links are relative to a schemas-ies/ page.
FAMILIES: dict[str, dict] = {
    "ElectricityCredential": {
        "category": "Verifiable Credentials",
        "used": "[Consumer Energy Passport](../use-cases/consumer-energy-passport/README.md) · "
                "[DER Visibility](../use-cases/der-visibility/README.md)",
    },
    "MeterDataCredential": {
        "category": "Verifiable Credentials",
        "used": "[Consumer Meter Digest](../use-cases/consumer-meter-digest/README.md)",
    },
    "MeterDataRequestCredential": {
        "category": "Verifiable Credentials",
        "used": "[Smart Meter Data Exchange](../use-cases/smart-meter-data-exchange/README.md) (optional consent proof)",
    },
    "MeterData": {
        "category": "Data Exchange payloads",
        "used": "[Smart Meter Data Exchange](../use-cases/smart-meter-data-exchange/README.md) · "
                "[Consumer Meter Digest](../use-cases/consumer-meter-digest/README.md)",
    },
    "MeterDataRequest": {
        "category": "Data Exchange payloads",
        "used": "[Smart Meter Data Exchange](../use-cases/smart-meter-data-exchange/README.md)",
    },
    "ArrFiling": {
        "category": "Data Exchange payloads",
        "used": "[DISCOM Regulatory Filing](../draft/use-cases/discom-regulatory-filing/README.md)",
    },
    "OutageNotification": {
        "category": "Data Exchange payloads",
        "used": "— no IES use-case guide yet",
    },
}

CATEGORY_ORDER = ["Verifiable Credentials", "Data Exchange payloads"]
CATEGORY_BLURB = {
    "Verifiable Credentials": "W3C VC payloads — signed, durable records the holder keeps and "
                              "verifies independently of any network.",
    "Data Exchange payloads": "Structured, non-credential payloads exchanged over the network or "
                              "published as feeds.",
}

# Raw asset files a version dir may carry, in developer-table order.
ASSET_FILES = [
    ("attributes.yaml", "OpenAPI 3.1 source of truth"),
    ("schema.json", "compiled JSON Schema (Draft 2020-12) — validate against this"),
    ("context.jsonld", "JSON-LD context for semantic resolution"),
    ("vocab.jsonld", "RDF vocabulary with standards alignments"),
]


def _h(s: str) -> str:
    """Minimal HTML escape for text placed inside the catalog cards."""
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def cards_table(families: list[str]) -> str:
    """A grid of clickable cards — one per family — using GitBook's native
    ``<table data-view="cards">`` block. GitBook renders it as a responsive card
    grid (name → version → description, whole card links to the family page); any
    other renderer degrades it to a plain table, so it never breaks."""
    head = ('<table data-view="cards"><thead><tr>'
            '<th></th><th></th><th></th>'
            '<th data-hidden data-card-target data-type="content-ref"></th>'
            '</tr></thead><tbody>')
    rows = [head]
    for f in families:
        info = parse_readme(f)
        latest = current_version(f, versions_of(f))
        desc = _h(info["tagline"] or "")
        rows.append(
            f'<tr><td><strong>{f}</strong></td><td>{_h(latest)}</td><td>{desc}</td>'
            f'<td><a href="{f}.md">{f}.md</a></td></tr>'
        )
    rows.append("</tbody></table>")
    return "\n".join(rows)


def version_key(v: str) -> tuple:
    """Sort key for a 'v1.2' / 'v0.10' style dir name — numeric, newest first."""
    nums = re.findall(r"\d+", v)
    return tuple(int(n) for n in nums) if nums else (0,)


def versions_of(family: str) -> list[str]:
    """Version dir names (e.g. ['v1.2','v1.1','v1.0']) that carry a schema.json,
    newest first."""
    fam_dir = os.path.join(SCHEMAS_DIR, family)
    vers = [
        d for d in os.listdir(fam_dir)
        if d.startswith("v")
        and os.path.isdir(os.path.join(fam_dir, d))
        and os.path.exists(os.path.join(fam_dir, d, "schema.json"))
    ]
    return sorted(vers, key=version_key, reverse=True)


def current_version(family: str, vers: list[str]) -> str:
    """The version presented as current: the newest one whose status in the family
    README's Versions table is not a draft. A family whose only versions are drafts
    (a WIP family) keeps its newest as current."""
    noted = parse_versions_table(family)
    for v in vers:
        if "draft" not in noted.get(v, ("", ""))[0].lower():
            return v
    return vers[0]


def parse_readme(family: str) -> dict:
    """Pull the tagline (single-asterisk italic line), the Status line, and any
    WIP warning from a family README."""
    path = os.path.join(SCHEMAS_DIR, family, "README.md")
    tagline, status, wip = "", "", False
    if not os.path.exists(path):
        return {"tagline": tagline, "status": status, "wip": wip}
    with open(path, encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not tagline:
                m = re.match(r"^\*([^*].*[^*])\*$", s)
                if m:
                    tagline = m.group(1).strip()
            if not status and s.startswith("**Status:**"):
                status = s[len("**Status:**"):].strip()
            if "WORK IN PROGRESS" in s.upper():
                wip = True
    return {"tagline": tagline, "status": status, "wip": wip}


def overview_page(family: str) -> str:
    """Relative path (from a schemas-ies/ page) to the family's plain-language
    overview page, e.g. ElectricityCredential -> ../what-ies-provides/
    schemas-overview/electricity-credential.md."""
    slug = re.sub(r"(?<!^)(?=[A-Z])", "-", family).lower()
    return f"{OVERVIEW_DIR}/{slug}.md"


def parse_versions_table(family: str) -> dict[str, tuple[str, str]]:
    """{version: (status, notes)} from the family README's ``## Versions``
    table. The table is hand-maintained there; we reuse it verbatim so the
    developer page never invents version facts."""
    path = os.path.join(SCHEMAS_DIR, family, "README.md")
    out: dict[str, tuple[str, str]] = {}
    if not os.path.exists(path):
        return out
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = re.match(r"^\|\s*\[(v[\d.]+)\][^|]*\|([^|]*)\|([^|]*)\|", line)
            if m:
                out[m.group(1)] = (m.group(2).strip(), m.group(3).strip())
    return out


# ---- field tables -----------------------------------------------------------

# Abbreviations whose trailing period must not be treated as a sentence end.
_ABBREV = {"e.g", "i.e", "etc", "vs", "cf", "no", "al", "approx",
           "incl", "resp", "min", "max", "fig", "eq"}


def _first_sentence(s: str) -> str:
    """First sentence of ``s`` — a period ends the sentence only when it is at
    paren depth 0, followed by whitespace + an uppercase letter or '(', and not
    part of an abbreviation (so "e.g. Asia/Kolkata" and "(0.5)" stay intact)."""
    depth = 0
    n = len(s)
    for i, ch in enumerate(s):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth - 1)
        elif ch in ".!?" and depth == 0:
            j = i + 1
            if j >= n:
                break
            if s[j].isspace() and j + 1 < n and (s[j + 1].isupper() or s[j + 1] == "("):
                prefix = s[:i].split()
                if prefix and prefix[-1].lower() in _ABBREV:
                    continue
                return s[: i + 1].strip()
    return s.strip()


def simple_desc(prop: dict) -> str:
    """A plain-language, single-sentence description for the developer view.

    The canonical ``schemas/`` reference records the full standards basis (the
    ``x-standard`` ``Based on …`` line) and any backward-compat / edge-case notes.
    For this developer section we keep it simple: drop the standards provenance
    entirely and keep only the first sentence of the description — "what the
    attribute is", nothing more. The full text stays one click away on the
    linked canonical per-version README."""
    if not isinstance(prop, dict):
        return gft.DASH
    d = prop.get("description")
    if not d:
        return gft.DASH
    return _first_sentence(" ".join(str(d).split())) or gft.DASH


def _component_table(title: str, comp: dict, defs: dict, bold_label: bool) -> str:
    props, required = gft.resolve(comp, defs)
    rows = []
    for name, prop in props.items():
        if name == "@context":
            continue
        field = f"**`{gft.md_escape(name)}`** \\*" if name in required else f"`{gft.md_escape(name)}`"
        desc = simple_desc(prop)
        cell = gft.md_escape(desc) if desc != gft.DASH else gft.DASH
        rows.append((field, gft.md_escape(gft.type_str(prop, defs)), cell))
    if not rows:
        return ""
    # Current version uses ### headings (they surface in the page TOC); previous
    # versions use bold labels so the collapsed tables don't clutter the TOC.
    head = f"**{title}**" if bold_label else f"### {title}"
    lines = [head, "", "| Field | Type | Description |", "|---|---|---|"]
    lines += [f"| {f} | {t} | {d} |" for f, t, d in rows]
    lines.append("")
    return "\n".join(lines)


def field_tables(schema: dict, bold_label: bool = False) -> str:
    """One table per object component: the root payload (if it has properties)
    then each $defs entry."""
    defs = schema.get("$defs", {})
    parts = []
    if schema.get("properties"):
        parts.append(_component_table(schema.get("title", "Payload"), schema, defs, bold_label))
    for name, comp in defs.items():
        if isinstance(comp, dict) and ("properties" in comp or "allOf" in comp):
            t = _component_table(comp.get("title", name), comp, defs, bold_label)
            if t:
                parts.append(t)
    return "\n".join(p for p in parts if p)


# ---- developer resources ----------------------------------------------------

def dev_resources_table(family: str, ver: str) -> str:
    base = f"{PAGES_BASE}/{family}/{ver}"
    ver_dir = os.path.join(SCHEMAS_DIR, family, ver)
    rows = [("Field reference (README)", f"{base}/README.md", "human-readable field reference for this version")]
    for fname, note in ASSET_FILES:
        if os.path.exists(os.path.join(ver_dir, fname)):
            rows.append((f"`{fname}`", f"{base}/{fname}", note))
    if os.path.isdir(os.path.join(ver_dir, "examples")):
        rows.append(("`examples/`", f"{REPO_TREE}/{family}/{ver}/examples", "worked payloads"))
    out = ["| Resource | URL | Notes |", "|---|---|---|"]
    for label, url, note in rows:
        out.append(f"| {label} | [{url}]({url}) | {note} |")
    return "\n".join(out)


def version_files_cell(family: str, ver: str) -> str:
    """Compact ``[schema.json](…) · [attributes.yaml](…) · [examples](…)`` cell
    of raw-asset links for one version — canonical github.io URLs, plus the
    github.com tree for examples (directories are not listable on Pages)."""
    base = f"{PAGES_BASE}/{family}/{ver}"
    ver_dir = os.path.join(SCHEMAS_DIR, family, ver)
    links = []
    for fname in ("schema.json", "attributes.yaml"):
        if os.path.exists(os.path.join(ver_dir, fname)):
            links.append(f"[{fname}]({base}/{fname})")
    if os.path.isdir(os.path.join(ver_dir, "examples")):
        links.append(f"[examples]({REPO_TREE}/{family}/{ver}/examples)")
    return " · ".join(links) if links else gft.DASH


def versions_table(family: str, vers: list[str]) -> str:
    """One row per published version, newest first. The version cell links to
    the in-book per-version page (a nav child of this page); status and notes
    are lifted from the family README's Versions table; Files carries the
    raw-asset URLs."""
    noted = parse_versions_table(family)
    out = ["| Version | Status | Notes | Files |", "|---|---|---|---|"]
    for v in vers:
        status, notes = noted.get(v, (gft.DASH, gft.DASH))
        out.append(f"| [{v}](../schemas/{family}/{v}/README.md) | {status or gft.DASH} "
                   f"| {notes or gft.DASH} | {version_files_cell(family, v)} |")
    return "\n".join(out)


# ---- page assembly ----------------------------------------------------------

def family_page(family: str) -> str:
    meta = FAMILIES[family]
    info = parse_readme(family)
    vers = versions_of(family)
    latest = current_version(family, vers)

    schema_path = os.path.join(SCHEMAS_DIR, family, latest, "schema.json")
    with open(schema_path, encoding="utf-8") as f:
        latest_schema = json.load(f)

    L: list[str] = [FRONTMATTER, "", AUTOGEN, "", f"# {family}", ""]
    if info["tagline"]:
        L += [f"*{info['tagline']}*", ""]
    if info["wip"]:
        L += ["> ⚠️ **Work in progress — subject to change.** Field names, enums and interpretation "
              "are not final. Do not depend on it for production integrations yet.", ""]

    # At-a-glance
    L += ["| | |", "|---|---|"]
    L.append(f"| **Canonical base** | `{PAGES_BASE}/{family}` |")
    L.append(f"| **Current version** | **{latest}** |")
    if info["status"]:
        L.append(f"| **Status** | {info['status']} |")
    L.append(f"| **Category** | {meta['category']} |")
    L.append(f"| **Used in** | {meta['used']} |")
    L.append("")

    L += ["What this schema is for, in plain language — standards basis, design rationale, open "
          f"points: [{family} (Schemas Overview)]({overview_page(family)}).", ""]

    # Current version
    L += [f"## Developer resources — {latest} (current)", "", dev_resources_table(family, latest), ""]
    L += [f"## Field reference — {latest} (current)", "",
          "_A field name in **bold** with a trailing **\\*** is required; all others are optional. "
          "**Type** shows units for QuantitativeValue models. Descriptions are simplified to the plain "
          "meaning of each field — the per-version pages (see **Versions** below) carry the full "
          "text, standards basis and notes._", ""]
    L += [field_tables(latest_schema, bold_label=True), ""]

    # Versions
    L += ["## Versions", ""]
    L += ["Every published version stays reachable at its canonical URL — clients pin a version "
          "explicitly. Click a version for its full field reference.", ""]
    L += [versions_table(family, vers), ""]

    return "\n".join(L).rstrip() + "\n"


def catalog_page() -> str:
    L: list[str] = [
        FRONTMATTER, "",
        AUTOGEN, "",
        "# IES Schemas",
        "",
        "> One page per schema family: the current field reference, the canonical file URLs, and "
        "every published version. Use the search box (top) to find a schema or field across all "
        "of them.",
        "",
    ]
    for cat in CATEGORY_ORDER:
        fams = [f for f, m in FAMILIES.items() if m["category"] == cat]
        if not fams:
            continue
        L += [f"## {cat}", "", CATEGORY_BLURB[cat], "", cards_table(fams), ""]

    L += [
        "## External — DEG schemas IES uses",
        "",
        "Schemas defined and published outside this repository, canonical at "
        "[schema.nfh.global](https://schema.nfh.global). Their field reference is mirrored in "
        "[External Schemas](external.md).",
        "",
        "---",
        "",
        "## How versions work",
        "",
        "Every schema lives at `schemas/<Family>/v<version>/` with its own `attributes.yaml` (source "
        "of truth), compiled `schema.json`, `context.jsonld`, `vocab.jsonld`, `examples/` and a "
        "generated `README.md` field reference. A **non-breaking** change (additive, optional fields, "
        "new enum values) is absorbed by the same minor version; a **breaking** change (rename, "
        "removal, type or semantics change) is published in a new sibling version, never overwriting "
        "the old one. Old versions stay reachable — see **Versions** on each page.",
        "",
        "To propose a new schema or a change, see the "
        f"[proposal flow]({REPO_BLOB}/README.md#proposing-a-new-schema-or-a-change).",
    ]
    return "\n".join(L).rstrip() + "\n"


def build() -> dict[str, str]:
    """Return {abs_path: content} for every file this generator owns."""
    files = {os.path.join(OUT_DIR, "README.md"): catalog_page()}
    for family in FAMILIES:
        files[os.path.join(OUT_DIR, f"{family}.md")] = family_page(family)
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit non-zero if any file is stale (no writes)")
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    files = build()
    stale = False
    for path, content in files.items():
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        rel = os.path.relpath(path, ROOT)
        if current == content:
            print(f"unchanged: {rel}")
            continue
        stale = True
        if args.check:
            print(f"STALE: {rel} (run without --check to update)")
            continue
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"updated:   {rel}")
    if args.check and stale:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
