#!/usr/bin/env python3
"""Generate a Field / Type / Standard / Status reference table for a schema
version and embed it into that version's README.md.

Source of truth is the compiled ``schema.json`` (present in every version dir;
it already carries property descriptions and our ``x-*`` extensions). One table
is produced per object component — the root payload (when it has properties)
plus each ``$defs`` entry — so the README documents itself for energy experts.

Columns:
  Field       — the property name.
  Type        — derived from the JSON Schema (enum -> "a / b / c", array -> "list of X",
                $ref -> the model name, boolean -> "yes / no", string+format -> the
                format, else the JSON type). A QuantitativeValue-style {value, unit}
                model shows its units, e.g. "QVPower (W / kW / MW)".
  Standard    — the field's ``x-standard`` annotation (in attributes.yaml -> schema.json),
                or "—" when unset. This is curated domain metadata, not auto-derived.
  Status      — "Mandatory" if the field is in the component's ``required`` list, else
                "Optional".
  Description — the field's ``description`` from the schema (whitespace-collapsed).

The table is written between
  <!-- FIELD-TABLE:START ... -->  and  <!-- FIELD-TABLE:END -->
markers, so re-running refreshes in place (idempotent). If the markers are absent
the section is appended to the README.

Usage:
  python3 scripts/generate_field_tables.py schemas/OutageNotification/v0.1
  python3 scripts/generate_field_tables.py --all
  python3 scripts/generate_field_tables.py --all --check   # CI: fail if stale
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys

START = "<!-- FIELD-TABLE:START — auto-generated by scripts/generate_field_tables.py from schema.json; do not edit by hand -->"
END = "<!-- FIELD-TABLE:END -->"
DASH = "—"


def ref_name(ref: str) -> str:
    """Last path segment of a $ref, e.g. '#/$defs/Identifier' or an external
    URL '…#/components/schemas/GeoJSONGeometry' -> 'Identifier' / 'GeoJSONGeometry'."""
    return ref.split("/")[-1]


def unwrap_single_ref(prop: dict):
    """A property written as ``allOf: [{$ref: X}]`` (the pattern we use to attach
    a description to a $ref) — return X's ref string, else None."""
    allof = prop.get("allOf")
    if isinstance(allof, list) and len(allof) == 1 and isinstance(allof[0], dict) and "$ref" in allof[0]:
        return allof[0]["$ref"]
    return None


def type_str(prop: dict, defs: dict | None = None) -> str:
    defs = defs or {}
    if not isinstance(prop, dict):
        return DASH
    r = unwrap_single_ref(prop) or prop.get("$ref")
    if r:
        name = ref_name(r)
        target = defs.get(name)
        if isinstance(target, dict):
            # Inline a named enum's values (e.g. Phase -> "NONE / R / Y / B / ABC").
            if "enum" in target and "properties" not in target:
                return " / ".join(str(e) for e in target["enum"])
            # Surface the units of a QuantitativeValue-style model (a {value, unit}
            # object whose `unit` is an enum) -> "QVPower (W / kW / MW)".
            unit = (target.get("properties") or {}).get("unit")
            if isinstance(unit, dict) and isinstance(unit.get("enum"), list):
                return f"{name} ({' / '.join(str(u) for u in unit['enum'])})"
        # Other object refs keep their model name (they get their own table).
        return name
    if "enum" in prop:
        return " / ".join(str(e) for e in prop["enum"])
    for combiner in ("oneOf", "anyOf"):
        if isinstance(prop.get(combiner), list):
            alts = [type_str(s, defs) for s in prop[combiner]]
            seen = [a for i, a in enumerate(alts) if a != DASH and a not in alts[:i]]
            if seen:
                return " or ".join(seen)
    t = prop.get("type")
    fmt = prop.get("format")
    if isinstance(t, list):
        return " / ".join(t)
    if t == "array":
        return "list of " + type_str(prop.get("items", {}), defs)
    if t == "string":
        return fmt or "text"
    if t == "boolean":
        return "yes / no"
    if t in ("integer", "number", "object"):
        return t
    return t or DASH


def resolve(comp: dict, defs: dict, seen=None):
    """Merge properties + required across allOf / internal $ref inheritance."""
    seen = seen or set()
    props: dict = {}
    required: set = set()
    if not isinstance(comp, dict):
        return props, required
    for sub in comp.get("allOf", []):
        p, r = resolve(sub, defs, seen)
        props.update(p)
        required |= r
    ref = comp.get("$ref")
    if ref and ref.startswith("#/$defs/"):
        key = ref_name(ref)
        if key in defs and key not in seen:
            p, r = resolve(defs[key], defs, seen | {key})
            props.update(p)
            required |= r
    props.update(comp.get("properties", {}))
    required |= set(comp.get("required", []))
    return props, required


def md_escape(text: str) -> str:
    return str(text).replace("|", "\\|")


def desc_str(prop: dict) -> str:
    """Field description, whitespace-collapsed for a single table cell."""
    if not isinstance(prop, dict):
        return DASH
    d = prop.get("description")
    return " ".join(str(d).split()) if d else DASH


def component_table(title: str, comp: dict, defs: dict) -> str:
    props, required = resolve(comp, defs)
    rows = []
    for name, prop in props.items():
        if name == "@context":
            continue
        standard = prop.get("x-standard") if isinstance(prop, dict) else None
        rows.append((
            f"`{md_escape(name)}`",
            md_escape(type_str(prop, defs)),
            md_escape(standard) if standard else DASH,
            "Mandatory" if name in required else "Optional",
            md_escape(desc_str(prop)),
        ))
    if not rows:
        return ""
    out = [f"### {title}", "", "| Field | Type | Standard | Status | Description |", "|---|---|---|---|---|"]
    out += [f"| {f} | {t} | {s} | {st} | {d} |" for f, t, s, st, d in rows]
    out.append("")
    return "\n".join(out)


def build_block(schema: dict) -> str:
    defs = schema.get("$defs", {})
    parts = [
        START,
        "## Field reference",
        "",
        "_Auto-generated from `schema.json`. **Field**, **Type** (with units for "
        "QuantitativeValue models), **Status**, and **Description** are derived from the "
        "schema; **Standard** comes from each field's `x-standard` annotation (`—` when "
        "unset). One table per object._",
        "",
    ]
    # Root payload table (only when the root declares properties directly).
    if schema.get("properties"):
        parts.append(component_table(schema.get("title", "Payload"), schema, defs))
    for name, comp in defs.items():
        if isinstance(comp, dict) and ("properties" in comp or "allOf" in comp):
            tbl = component_table(comp.get("title", name), comp, defs)
            if tbl:
                parts.append(tbl)
    parts.append(END)
    return "\n".join(parts).rstrip() + "\n"


def embed(readme_path: str, block: str) -> str:
    with open(readme_path, encoding="utf-8") as f:
        text = f.read()
    if START in text and END in text:
        pre = text[: text.index(START)]
        post = text[text.index(END) + len(END):]
        return pre + block.rstrip("\n") + post
    # Append a new section at the end.
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + "\n---\n\n" + block


def process(version_dir: str, check: bool) -> bool:
    schema_path = os.path.join(version_dir, "schema.json")
    readme_path = os.path.join(version_dir, "README.md")
    if not (os.path.exists(schema_path) and os.path.exists(readme_path)):
        return True
    with open(schema_path, encoding="utf-8") as f:
        schema = json.load(f)
    block = build_block(schema)
    with open(readme_path, encoding="utf-8") as f:
        current = f.read()
    updated = embed(readme_path, block)
    if updated == current:
        print(f"unchanged: {readme_path}")
        return True
    if check:
        print(f"STALE: {readme_path} (run without --check to update)")
        return False
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(updated)
    print(f"updated:   {readme_path}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("dirs", nargs="*", help="schema version dir(s) (containing schema.json + README.md)")
    ap.add_argument("--all", action="store_true", help="process every schemas/*/v*/ version dir")
    ap.add_argument("--check", action="store_true", help="exit non-zero if any README is stale (no writes)")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if args.all:
        dirs = sorted(os.path.dirname(p) for p in glob.glob(os.path.join(root, "schemas", "*", "*", "schema.json")))
    else:
        dirs = args.dirs
    if not dirs:
        ap.error("pass one or more version dirs, or --all")

    ok = all(process(d, args.check) for d in dirs)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
